name: Selenium Tests

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker environment
      run: |
        docker pull selenium/standalone-chrome:latest

    - name: Create Selenium container
      run: |
        docker create --name selenium_chrome --network github_network --network-alias selenium -p 4444:4444 --shm-size 2g -e GITHUB_ACTIONS=true -e CI=true selenium/standalone-chrome:latest

    - name: Start Selenium container
      run: docker start selenium_chrome

    - name: Run your tests
      run: |
        # Your test execution logic goes here
        echo "Running tests"

    - name: Stop and remove Selenium container
      run: |
        docker stop selenium_chrome
        docker rm selenium_chrome
