name: Maven Selenium Tests

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt' # Options: 'zulu', 'adopt', 'adopt-hotspot', 'adopt-openj9', etc.

      # Cache Maven dependencies to speed up the build
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Install Maven dependencies
      - name: Install Dependencies
        run: mvn install -DskipTests

      # Run the tests
      - name: Run Selenium Tests
        run: mvn test
